---
- name: install epel-repo
  yum: name=epel-release state=latest

- name: install python-pip
  yum: name=python-pip state=present

- name: upgrade pip
  pip: name=pip state=latest

- name: install docker-compose
  pip: name=docker-compose state=latest

