---
- name: Get docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.10.1/docker-compose-{{ansible_system}}-{{ansible_machine}}"
    dest: /usr/bin/docker-compose
    mode: 0755
