---
- name: install docker repo
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo force=no    

- name: install docker-engine
  yum: name=docker-engine state=latest

- name: start docker
  service: name=docker state=started

- name: enable docker
  service: name=docker enabled=yes

